### ISSUE TITLE
splash page link for wiki is 404 missing

### ISSUE THREAD

**Issue by goephs** [atsa-es/MARSS#155]
**Error message**
404 file not found. The site configured at this address does not contain the requested file.

**Code to reproduce**
Splash page: https://nwfsc-timeseries.github.io/MARSS/
has incorrect link for wiki: https://atsa-es.github.io/MARSS-wiki/
correct link for wiki seems to be this: https://nwfsc-timeseries.github.io/MARSS-wiki/

**Comment by eeholmes** [comment]
Thanks! Fixed. I'd forgotten to move the MARSS-wiki repo over to the new atsa-es GitHub organization.
