### ISSUE TITLE
Question regarding error in Q matrix

### ISSUE THREAD

**Issue by camrynblawas** [atsa-es/MARSS#191]
I am hoping to create a MARSS model that allows for correlation between the local processes as well as a shared stochastic level process. I think in order to do that I need to create a Q matrix that accounts for this correlation, but I keep running into the same error: "Errors were caught in is.marssMODEL_marxss(). The variance-covariance matrix Q is not properly constrained. matrix is not symmetric and all varcov matrices are at t=1"

Any help or advice would be fantastic! Here is a reproducible example in R: 

library(MARSS)

## Example data
dat <- matrix(rnorm(100), ncol = 10)

n <- 10  

B <- "identity"
A <- "zero"
Z <- cbind(1,diag(1,n))
R <- "diagonal and equal"
U <- matrix(list(0),n+1,1)
U[1] <- "u"
x0 <- matrix(list(0),n+1,1)
x0[2:(n+1)] <- paste0("x0.",1:n)

## Define the Q matrix
Q <- matrix(list(0),n+1,n+1)
Q[1,1] <- "qa"
Q2 <- matrix("q",n,n)
diag(Q2) <- paste0("q", 1:n)
Q2[upper.tri(Q2)] <- paste0("c",1:n)
Q2[lower.tri(Q2)] <- paste0("c",1:n)
Q[2:(n+1),2:(n+1)] <- Q2

## Define the model list
mod.list2 <- list(B = B, A = A, Z = Z, Q = Q, R = R, U = U, x0 = x0, tinitx = 0)

## Fit the model using the MARSS function
fit.mod2 <- MARSS(dat, model = mod.list2)

**Comment by eeholmes** [comment]
Hi! If you look at the Q that your code produces, there is a bug and the Q matrix is not symmetric (as the error message alerts you to) nor are all the correlations unique, which they must be for your case.
<img width="495" alt="image" src="https://github.com/atsa-es/MARSS/assets/2545978/5e679255-7588-40e9-a736-e796ebafc736">

The following code will create the symmetric Q:
```
Q <- matrix(list(0),n+1,n+1)
Q[1,1] <- "qa"
Q2 <- matrix("q",n,n)
diag(Q2) <- paste0("q", 1:n)
Q2[upper.tri(Q2)] <- paste0("c",1:(n*(n-1)/2))
Q2[lower.tri(Q2)] <- t(Q2)[lower.tri(t(Q2))]
Q[2:(n+1),2:(n+1)] <- Q2
```

<img width="556" alt="image" src="https://github.com/atsa-es/MARSS/assets/2545978/b22f7c8e-70b1-4945-93a2-31262bebf776">
