### ISSUE TITLE
broken link to quick start guide

### ISSUE THREAD

**Issue by WaterLynn** [atsa-es/MARSS#192]
Feel free to ask us questions about how to use MARSS models or syntax.
on main page
link - https://cran.r-project.org/package=MARSS/vignettes/Quick_Start.pdf
appears to be broken 

using chrome on PC to browse and does not work

**Comment by eeholmes** [comment]
Thanks! Fixed. Should be https://cran.r-project.org/web/packages/MARSS/vignettes/Quick_Start.html
